### ISSUE TITLE
Achievement based on number of quest realized

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#232]
## Descritpion

1 - 5 of Quests realized 
2 - 10 Quests realized
3 - 20 Quests realized

## TODO

- [ ] Make an endpoint to know the total number of quests
- [ ] Add Building on the front-end
- [ ] Add Achievement in Database testnet
- [ ] Add Achievement in Database mainnet

**Comment by fricoben** [comment]
This is moved to another issue that @ayushtom is doing
