### ISSUE TITLE
Add Rango Exchange Quest

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#280]
## Tasks to create 

- [ ] Quizz about rango
- [ ] Twitter Follow
- [ ] Join Rango Discord
- [ ] Do at least 25$ dollar of any assets with AVNU on Rango exchange.

You can find quest brief here https://app.skiff.com/file/80cc04dc-d538-467d-9a92-542f905afa81 (some infos are missing but you have most of it
