### ISSUE TITLE
Create Nostra Finance Quest

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#281]
## Tasks to create 

- [ ] Quiz made by Gurk (link here soon)
- [ ] Provide collateral on Nostra
- [ ] Join Nostra Discord
