### ISSUE TITLE
Add CL mySwap quest (second braavos score quest)

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#291]
## Description
Add Braavos score number 2 quest with mySwap concentrated liquidity contract

## TASKS
- [ ] Copy-paste the first Braavos score quest
- [ ] Add the mySwap concentrated liquidity task after the  
- [ ] Delete the crew3 task (because it doesn't work so well)
- [ ] Ask Braavos about the NFT and add it to the front-end
- [ ] Test on the testnet
- [ ] Add everything to the database on mainnet
- [ ] @fricoben test on mainnet

Quest task should be 
- Domain or Braavos domain 
- Myswap provide liquidity
- Follow mySwap
- Follow Braavos
