### ISSUE TITLE
Chest Achievement & Opening SQ

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#314]
## Description

We want to create a new achievement that checks a user's completed quest number. 

Each time the user makes the required amount he'll be able to open a chest to earn a special land that can be common, rare, or epic.

## Todo
- [ ] Prepare the necessary back-end and propose a way to do it to Thomas (if needed)
- [ ] Add an achievement with 5 milestones: 1 quest, 3 quests, 10 quests, 25 quests and 50 quests. 
- [ ] Create the front-end opening screens 
- [ ] Add the necessary buildings made for this feature to the app (you can talk to HP to have them). [Here](https://app.skiff.com/file/33660e7f-e2af-4634-81ba-e9ec3ba670a6) is the documentation about the land part and @irisdv can help you if needed.

**Comment by Th0rgal** [comment]
Hey,

The way achievements page work is that it will first query all the achievements you've done. Then for every category not fully completed, it will query the server to ask it to check if you didn't complete an achievement, if you did it will continue with the next achievement until it reaches the end of the category or find an achievement that you didn't complete.

The logic for checking and validating achievements can be found here on the client side:
https://github.com/starknet-id/starknet.quest/blob/testnet/app/achievements/page.tsx#L64 

On the database, the `verify_type` field specifies which endpoint to call. Usually it's the endpoint `verify_default` but you can find all the other ones in the same folder:
https://github.com/starknet-id/api.starknet.quest/blob/master/src/endpoints/achievements/verify_default.rs#L58

In the later you can see we simply return `{ achieved: true/false }`. Here what we want to do is to not only complete the achievement, but allow the user to claim something once (a NFT). My suggestion is to add a field `claimable` to the achievements collection documents (which can be empty or contain information about what you want to claim, e.g. `{ claim_endpoint_type: nft, claim_endpoint: /claim_x }` .
When that information is empty, you would always return { achieved, claimed } where claimed is the same value as achieved (this means that the achievement is automatically claimed, that's the current behavior), however, for that specific achievement, you would return true only if there is a document in newly created "claimed_achievement" collection with the user address. On the frontend, this field will be useful for you to display the claim button (if it is false, you can display it).

You will then create a new endpoint (the one specified in `claim_endpoint` field from the achievements collection), when it is called (when clicking on the button), this will give the reward to the user and return a json containing the reward_type and some additional info. For a NFT like here, the reward type could be "nft" and a signature to mint it from our contract, the frontend will have to match on the reward type and use the info to give the user the reward.

**Comment by ayushtom** [comment]
https://github.com/starknet-id/starknet.quest/issues/570#issuecomment-2028748233
