### ISSUE TITLE
Add All Contributors bot front-end

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#857]
## Description
We want to recognize all contributors to this project using the All Contributors bot. This will automate the process of adding contributors to our README.md file.

## Tasks
- [x] 1. Add the All Contributors bot to the repository
- [ ] 2. Set up the initial configuration
- [ ] 3. Update the README.md file with the contributors section
- [ ] 4. Document the process for contributors to add themselves

## Implementation Details

1. Create a `.all-contributorsrc` file in the root of the repository with the following content:

```json
{
  "files": ["README.md"],
  "imageSize": 100,
  "commit": false,
  "contributors": [],
  "contributorsPerLine": 7,
  "projectName": "Starknet Quest",
  "projectOwner": "lfglabs-dev",
  "repoType": "github",
  "repoHost": "https://github.com",
  "skipCi": true,
  "commitConvention": "none"
}
```
2. Add the following section to your README.md file:

```md
Contributors ✨
Thanks goes to these wonderful people 1:
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->
<!-- ALL-CONTRIBUTORS-LIST:END -->
This project follows the all-contributors specification. Contributions of any kind welcome!
```
3. Add instructions for contributors in the README.md file:

```md
## Adding yourself as a contributor

If you've contributed to this project, you can easily add yourself to the contributors list by commenting on any issue or pull request with: `@all-contributors please add <your-github-username> for <contribution-type>`

For example: `@all-contributors please add @fricoben for code, business, and ideas`
 
For a full list of contribution types, check out the [emoji key](https://allcontributors.org/docs/en/emoji-key).
```

After implementing these changes, the All Contributors bot will be set up and ready to use in our repository you can test to add yourself as a contributor

**Comment by Naomi-Gift** [comment]
@fricoben can I work on this?

**Comment by raizo07** [comment]
Hello I'll like to work on this 

Estimated time: One hour


I've implemented this for a couple of projects on Starknet like StrkFarm, Karst and recently Web3 Wagers

**Comment by Ugo-X** [comment]
@fricoben  Would like to work on this

**Comment by deeseeker** [comment]
I want to to work on this task.

ETA- 2-3days

**Comment by od-hunter** [comment]
Hi @fricoben , can I be assigned this please?

**Comment by martinvibes** [comment]
**hello @fricoben i would love to work on this issue** Kindly Assign :)

**Comment by Benjtalkshow** [comment]
@fricoben Can I be assigned to this task? I will deliver a quality work. Thanks

**Comment by josephchimebuka** [comment]
Hello @fricoben can I handle this pls I would I would follow the implementation details to get this done in 2 days ser
