### ISSUE TITLE
Delete partnership page

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#950]
## Description 📹

We need to remove the partnership page and all its related code from the repository as it's no longer needed. This includes the page itself, associated components, styles, and any unused assets.

## Files to Remove 🗑️

1. Main Partnership Page:
```app/partnership/page.tsx
// Entire file to be removed
```

2. Partnership Styles:
```styles/partnership.module.css
// Entire file to be removed
```

3. Footer Link to Partnership:
```components/footer/footer.tsx
// Remove partnership link from navigation
```

4. Remove unused assets:
- `/public/visuals/partners/partnershipHeader.webp`
- `/public/visuals/partners/getYourStarkDomain.webp`
- `/public/visuals/partners/buildYourStarknetLand.webp`
- `/public/visuals/partners/airdropsAreSo2021.webp`
- `/public/visuals/partners/meaningfulRewards.webp`
- `/public/visuals/partners/sybilResistantMarketing.webp`
- `/public/partners/braavosLogo.svg`
- `/public/partners/zklendLogo.svg`
- `/public/partners/sithswapLogo.svg`
- `/public/partners/jediswapLogo.svg`
- `/public/partners/avnuLogo.svg`

## Proposed Actions 🛠️

1. **Fork and Create Branch**:  
```bash
git checkout -b fix-[issue-number]
```

2. **Implementation Steps**:
   - [ ] Remove the partnership page file
   - [ ] Remove the partnership styles file
   - [ ] Remove the partnership link from the footer
   - [ ] Remove all unused partner assets from the public directory
   - [ ] Update any imports or references to these files
   - [ ] Test the application to ensure no broken links or references remain

3. **Run Tests and Commit Changes**:  
```bash
git commit -m "Fix: Remove partnership page and related code"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren't assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by mexes20** [comment]
Can I be assigned to work on this?

**Comment by No-bodyq** [comment]
Hello @fricoben can I work on this

**Comment by Yunusabdul38** [comment]
@fricoben I'd like to work on this issue to implement the necessary changes

**Comment by martinvibes** [comment]
Hey @fricoben would like to do this ASAP

**Comment by vestor-dev** [comment]
Can I be the one to work on this issue @fricoben

**Comment by omsant02** [comment]
i would like to work on this issue @fricoben 
i am a new contributor for this repo and want to start my journey with starknet.quest

i have an experience with nextjs and page router
ETA : 1 day
thank you

**Comment by trashcancries** [comment]
gm @fricoben, I am new to starknet quest and would like to start contributing here with this issue, please assign.

**Comment by Villarley** [comment]
hey @fricoben,
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features. I already contributed to this project, so I'm able to deliver faster thanks to my knowledge of the project.
I would follow all the instructions and deliver the best quality.🚀🚀

**Comment by wheval** [comment]
Hello @fricoben, I'm wheval a frontend developer. This should be pretty straightforward.
I would find the Partnership page and its styles in the codebase and remove it. I would also remove each of the icons listed in this issue. 
Also, i would check for any import that uses the deleted files to ensure nothing is broken. I would also remove the partnership page from the navigation link.
Finally, i would test it locally to ensure that the nothing broke and the build compiles.

ETA is <4hrs

**Comment by pheobeayo** [comment]
Hello @fricoben 
I am a web3 frontend developer skilled in Next js, React js, JavaScript, TypeScript, Rust, Cairo. 
I have contributed successfully to api- starknet quest and other projects on Only Dust.
I will run the codes, and remove the partnership page as requested. I will remove the link and unused assets as requested. I will test locally and ensure proper compilation of the codebase

**Comment by OWK50GA** [comment]
Hi, @fricoben thank you for stating the guidelines clearly. I can work on these

**Comment by Benjtalkshow** [comment]
Can I take care of this issue?

**Comment by Emmanex01** [comment]
Can I start working on this?

**Comment by aurlic** [comment]
Hey, I would be happy to help with this issue. I have done many projects using GitHub and know I could do this fast. Thank you in advance !

**Comment by Akshola00** [comment]
Can I work on this, please?

**Comment by blessingbytes** [comment]
Hi @fricoben pls i would love to be assigned this issue , and i promise to deliver

**Comment by SYLVIANNORUKA** [comment]
Could I take over this issue?
I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Supa-mega** [comment]
I'd like to take this issue.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by SudiptaPaul-31** [comment]
Will love to work on this issue.

**Comment by ShantelPeters** [comment]
I’d like to help with this.

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. to solve this I’ll create a new branch, delete the partnership page and its styles, remove the link from the footer, and clean up all unused partnership assets from the `/public` directory. Then, I’ll update any code references to these files, test the app to ensure there are no broken links or errors, and commit the changes with a clear message before pushing the branch and opening a pull request. I would really love to be assigned this issue and work on this project.

**Comment by ONEONUORA** [comment]
Can i fix this?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️. I’d love to contribute to this project! I’m highly detail oriented and enjoy working through new code, which gives me confidence that I can complete this issue efficiently.

My workflow:

- Remove partnership page, styles, and assets
- Update footer and fix broken references
- Test and commit changes per guidelines

ETA: 24 hrs

**Comment by Amarjeet325** [comment]
Hi , I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me?

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by Ekene001** [comment]
Please Could I be assigned to this issue?

**Comment by sotoJ24** [comment]
Thank you for providing detailed instructions for this task. I understand the scope of work, including removing the partnership page, associated styles, and unused assets, as well as updating references and ensuring no broken links remain.

### Action Plan:

**Fork and Create Branch:**

I will start by creating a new branch as per the naming convention: fix-Delete Partership Page[#950].

**Implementation Steps:**

- Remove the partnership page file and related styles.
- Delete the footer link pointing to the partnership page.
- Remove all unused partner assets listed in the issue description.
- Verify and update any imports or references across the repository to prevent broken references.

 **Testing:**

- Test the application locally to ensure the changes don’t cause regressions.
- Run all relevant tests to confirm functionality.
- 
 **Commit and Push:**


Once all tasks are complete and verified, I’ll commit changes with the message: Fix: Remove partnership page and related code.
Submit Pull Request:

I will create a PR and ensure the description includes Close #[950] to automatically close the issue upon merging.

Josué From Dojo Coding

**Comment by akintola4** [comment]
Mind if I take this issue?i would be really happy if I'm assigned this task and e able to help the community, this a link to my twitter https://x.com/photofola
i could be able to learn from this experience too since I'm a self taught developer

**Comment by akintola4** [comment]
Mind if I take this issue?i would be really happy if I'm assigned this task and e able to help the community, this a link to my twitter https://x.com/photofola
i could be able to learn from this experience too since I'm a self taught developer  and a link to my recent two works for designers i work with. (https://ooido-kc4l.vercel.app/) & (https://webfleets.vercel.app/)

**Comment by josephchimebuka** [comment]
Could I take a shot at this?

**Comment by akdavis83** [comment]
I'd love to tackle this!

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, 
I would love to get assigned with this issue

**Comment by aspiringLilCoder** [comment]
Can I attempt this issue?
