### ISSUE TITLE
Simplify our wallet management system by creating a centralized configuration 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#953]
## Description 📹

We need to simplify our wallet management system by creating a centralized configuration approach similar to the reference implementation. This will make the codebase more maintainable and easier to update when adding new wallets.

This issue is inspired by the [Starknet ID model for managing wallets](https://github.com/lfglabs-dev/app.starknet.id/blob/testnet/utils/connectorWrapper.ts), you can refactor with the same architecture and reusing the same functions.

## Current Issues 🔍

1. Wallet configurations are scattered across multiple files
2. Redundant wallet information in different components
3. No centralized way to manage wallet metadata (icons, names, download links)
4. Complex conditional rendering in wallet icons component

## Files to Update 🔄

1. Create new utility file `utils/walletConfig.ts`:
```typescript
// Centralized wallet configuration
export const wallets = [
  {
    id: "argentX",
    name: "Argent X",
    icon: `data:image/svg+xml;base64,...`, // Icon data
    downloads: {
      chrome: "https://chrome.google.com/webstore/detail/...",
      firefox: "https://addons.mozilla.org/...",
      edge: "https://microsoftedge.microsoft.com/..."
    },
    website: "https://www.argent.xyz/argent-x/"
  },
  // Add other wallets...
];

export const getConnectors = () => {
  // Return configured connectors
};

export const getWalletInfo = (id: string) => {
  return wallets.find(wallet => wallet.id === id);
};
```

2. Update `app/provider.tsx`:
```typescript
// Simplify connector configuration using new utility
import { getConnectors } from '@utils/walletConfig';

export const availableConnectors = getConnectors();
```

3. Update `components/UI/iconsComponents/icons/walletIcons.tsx`:
```typescript
// Simplify icon rendering using centralized config
import { getWalletInfo } from '@utils/walletConfig';

const WalletIcons: FunctionComponent<WalletIconsProps> = ({ id }) => {
  const walletInfo = getWalletInfo(id);
  return walletInfo?.icon ? (
    <img src={walletInfo.icon} alt={walletInfo.name} className={styles.button_icon} />
  ) : null;
};
```

## Implementation Steps 📝

1. [ ] Create new `walletConfig.ts` utility file
2. [ ] Move all wallet configurations to the central config
3. [ ] Update provider.tsx to use new configuration utility
4. [ ] Simplify WalletIcons component to use central config
5. [ ] Update any components that reference wallet information
6. [ ] Add utility functions for getting wallet metadata
7. [ ] Add proper TypeScript types for wallet configurations
8. [ ] Update tests to reflect new structure
9. [ ] Test that all wallet connections are working

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren't assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by PedroCo3lho** [comment]
Hello @fricoben,
I’m a full-stack developer with a solid understanding of TypeScript, Next.js, and TailwindCSS. I have previously implemented StarknetKit in dApps. The requirements and development flow are clear to me. I’m looking forward to your approval and would love to work on this issue. 
Please let me know if I can start so I can deliver it asap!

**Comment by zintarh** [comment]
I would love to work this issue

**Comment by lauchaves** [comment]
Hey, guys @fricoben @Marchand-Nicolas  👋 Im Lau Chaves from dojo coding, I have contributed before and would like to give a hand again! 

Feel free to check [my only dust profile ](https://app.onlydust.com/u/lauchaves) and my GitHub profile. I'm a full-stack engineer with over five years of experience. I started contributing and learning Web3 this year and have contributed to several projects already! 

I would make the utils file for the wallet configurations and I'd follow all the steps mentioned in the ticket ensuring everything works as expected 🚀

**Comment by Abeeujah** [comment]
Hi, the end goal and implementation steps is pretty detailed, I'd love to work on this!

**Comment by snehaa-eth** [comment]
Hey, I have contribute before and worked on the argent wallet before on this repo so i can easily take this up and also before in other i have worked with intergrations of other wallet like phantom,metamask,nightly

**Comment by Benjtalkshow** [comment]
Hello @fricoben
i am willing to tackle this task. I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js, TypeScript and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions. i would love to simplify the wallet management system by creating a centralized file to configure all the wallet related configs. My ETA is 3days. Thanks

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Supa-mega** [comment]
Mind if I take this issue?

**Comment by wheval** [comment]
Hello @fricoben, I'm Wheval an experienced frontend developer. 

I can fix this issue of redundant connect wallet logic in multiple files. 
Here's how I would do it,
I would use the Starknet ID model linked above to create a centralized walletConfig.ts file for managing the wallets.
I would move all wallet configurations to the walletConfig file and refactor the WalletIcon component to use the central config. I would also create proper types for the wallet data.
I would also add utility functions for getting wallet metadata to the utils file.
I would update the tests appropriately and test that the connections are working.

Please assign. Thank you!


ETA is 2 days.

**Comment by PedroCo3lho** [comment]
> Hello @fricoben, I’m a full-stack developer with a solid understanding of TypeScript, Next.js, and TailwindCSS. I have previously implemented StarknetKit in dApps. The requirements and development flow are clear to me. I’m looking forward to your approval and would love to work on this issue. Please let me know if I can start so I can deliver it asap!

Can I be assigned to this?

**Comment by ShantelPeters** [comment]
Can I start working on this?

**Comment by Ekene001** [comment]
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table.

To tackle this issue, I will create a new utility file, utils/walletConfig.ts, to store all wallet configurations in one centralized location. This will include details like id, name, icon, and downloads. I’ll also add utility functions, like getConnectors and getWalletInfo, to pull and retrieve specific wallet data.

Next, I will refactor the app/provider.tsx file to use these new utility functions, simplifying how wallet connectors are configured. This will make it easier to add or remove wallets by modifying just the configuration file.

I will also update the wallet icon component in walletIcons.tsx to pull wallet information directly from walletConfig.ts, eliminating complex logic for rendering icons. This will simplify the component and ensure consistency across the app.

**Comment by Michaelkingsdev** [comment]
I can handle this.

**Comment by JoE11-y** [comment]
Can I jump on this task?

**Comment by Amarjeet325** [comment]
I'd love to work on this!
